### ISSUE TITLE
ej01 normal maps: which direction?

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/tex-ej01_src.dpkdir#1]
While investigating [parallax mapping](https://github.com/DaemonEngine/Daemon/issues/30), I discovered the fact [DirectX and OpenGL normalmaps are reverted together](https://answers.arnoldrenderer.com/questions/169/why-do-my-normal-maps-appear-to-be-inverted.html).

@EmperorJack, do you know if you intended to do the ej01 normal maps the DirectX way or the OpenGL way or did you intended nothing?

**Comment by EmperorJack** [comment]
Hey @illwieckz - I can't say for sure but I do vaguely remember having to invert an axis in blender when baking out my maps. So perhaps whatever blender uses is what I had to account for. Is it possible there could be an issue in the future with this?

**Comment by illwieckz** [comment]
Basically to switch from DirectX to OpenGL format or to go the other way is just a matter of inverting the green channel in normal map files. So, it's not a big issue if some existing files are in wrong compared to what engine expects or if we have to change the direction the engine expects. But if we have to fix something, either in assets, either in engine, it's better to not do it in years. :grin: 

Basically, while toying with xonotic assets I discovered that our engine expects the xonotic normalmap and heightmaps to be reverted to be rendered correctly, and for heightmaps, now I'm sure our engine is wrong. For normal map there is no wrong or right direction, there is just two standards and we have to live with it.

Among Darkplaces and Dæmon engine I'm trying to tell which one is doing things the DirectX way and which one is doing things the OpenGL way…

**Comment by EmperorJack** [comment]
Thanks for the info, this makes sense. Let me know if there is any other
questions I can answer for you.

**Comment by illwieckz** [comment]
After some analysis, it appears the green orientation follows the DirectX convention (-Y) which is the native orientation for the Dæmon engine, because XreaL did it that way, because Doom 3 did it that way.
